### ISSUE TITLE
Add posts table

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-dashboard-remix#1]
Add posts table in post page
- api endpoint `/posts`
- populate incomming data from api in table

**Comment by nirajpdn** [comment]
I want to work on this.

**Comment by nirajpdn** [comment]
- [x] Solved: 
`/posts` endpoint is not working.
```
{
"type": "error",
"message": "API endpoint does not exists",
"data": null
}
```
I was confused in endpoints, its solved now.

**Comment by harshmangalam** [comment]
Use `ENDPOINT/posts`

**Comment by harshmangalam** [comment]
ENDPOINT is a constant pointing to admin url

**Comment by harshmangalam** [comment]
Done by @nirajpdn
