### ISSUE TITLE
Add group post table

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-dashboard-remix#4]
Add a table in groups post page

- group post api path /groupPosts
- populate group posts table information comming from api

**Comment by PranjalAgni** [comment]
Hi @harshmangalam, I can work on this issue

**Comment by harshmangalam** [comment]
Okay make PR i will merge.

**Comment by PranjalAgni** [comment]
Hi @harshmangalam, what exact parameters do we need to provide to this endpoint to fetch the group posts?  
I am getting the below error when directly calling this API

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/26196076/195414523-11b834f2-81a4-4324-8b7f-d369db371c14.png">

**Comment by harshmangalam** [comment]
Just i fixed this issues you can check now

**Comment by PranjalAgni** [comment]
Sure thanks
