### ISSUE TITLE
Add notification table

### ISSUE THREAD

**Issue by harshmangalam** [harshmangalam/hydrogen-dashboard-remix#5]
Add a table in notifications page

- Notification api path `/notifications`

**Comment by KatarinaChavkova** [comment]
Hi, can be this issue assigned to me? other one was closed by you.

**Comment by harshmangalam** [comment]
Sure make a PR will merge your request

**Comment by KatarinaChavkova** [comment]
what do you mean?

**Comment by harshmangalam** [comment]
Work on feature and make Pull Request i will merge your request

**Comment by nirajpdn** [comment]
I want to do this. Assign this to me.

**Comment by nirajpdn** [comment]
@harshmangalam , can you close this issue and create other issues. I can work on other pages and features.

**Comment by harshmangalam** [comment]
Okay
